config/routes.rb
Iqm::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :trainings do
    get 'offer', on: :collection
    post 'create_from_exemplary', on: :member
    resources :orders do
      collection do
        get   'register'
        post  'preview'
        post  'confirm'
      end
    end
  end

  resources :segments

  resources :event_types do
    resources :segments, only: :index
  end

  resources :companies

  resources :clients

  resources :orders

  resources :offers, shallow: true do
    resources :quotes do
      resources :income_variants,:cost_items
    end
  end

  root to: 'offers#index'

end

app/models/training.rb
# encoding: utf-8
# == Schema Information
#
# Table name: trainings
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  start_date       :date
#  end_date         :date
#  city             :string(255)
#  price_per_person :integer
#  training_type_id :integer
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#

class Training < ActiveRecord::Base
  has_many :event_type_trainings, dependent: :destroy
  has_many :training_types, through: :event_type_trainings, source: :event_type  

  has_many :training_segments, dependent: :destroy
  has_many :segments, through: :training_segments

  has_many :order_items, as: :productable, include: :seats

  has_many :training_products
  has_many :products, through: :training_products

  accepts_nested_attributes_for :training_segments

  attr_accessible :city, :end_date, :name, :price_per_person, :start_time, :training_type_ids, :number_of_days, 
                  :number_of_hours, :segment_ids, :training_segments_attributes, :introduction, :exemplary, :description

  scope :exemplary, where(exemplary: true)
  scope :real, where(exemplary: false)

  amoeba do
    enable
    include_field :training_segments
    include_field :event_type_trainings
    include_field :training_products
    set exemplary: "false"
  end

  def book
    products.first if self.has_book?
  end

  def has_book?
    !products.empty?
  end

  def price
    self.price_per_person
  end

  def craft!(event_types)
    event_types.each do |event_type|
      self.add_event_type(event_type)
      self.add_segments_from(event_type)
    end
    self.save!
  end

  def add_segments_from(event_type)
    event_type.segments.each do |et_s|
      ts = self.training_segments.build(segment_id: et_s.id)
      ts.name = et_s.name
      ts.scenario = et_s.scenario
      ts.number_of_hours = et_s.number_of_hours
      ts.lineup = et_s.default_lineup
    end
  end

  def add_event_type(event_type)
    self.training_types << event_type
    self.name.nil? ? (self.name = event_type.name) : (self.name << (" " + event_type.name))
    self.description      =  self.description.to_s << event_type.description
    self.number_of_days   =  self.number_of_days.to_i 
    self.number_of_days   += event_type.default_number_of_days
    self.price_per_person =  self.price_per_person.to_f 
    self.price_per_person += event_type.default_price_per_person
  end

  def schedule

    order_by = if self.exemplary
      "lineup ASC"
    else
      "start_time ASC, lineup ASC"
    end

    segs = self.training_segments.order("#{order_by}")

    ret_string = ""
    
    segs.each do |s|      
      ret_string << s.scenario
      ret_string << "(#{s.number_of_hours} godz.)<br/>"
      ret_string << "<strong>Data: #{s.start_time.strftime("%d-%m-%Y")}</strong>" if s.start_time
    end

    ret_string

  end

  def closest_trainings
    if self.exemplary
      "Najbliższe szkolenia"
    else
      nil
    end
  end

  def set_start_time
    new_start_time = self.training_segments.order("start_time ASC").first.try(:start_time)
    self.update_attribute(:start_time, new_start_time) if new_start_time
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  before_filter :authorize, except: [:offer, :index, :show]
  
  def offer
    @trainings = Training.exemplary
    @training_months = Training.real.group_by { |t| t.start_time.beginning_of_month }
  end

  def index
    @trainings = Training.real
    @training_months = @trainings.group_by { |t| t.start_time.beginning_of_month }
  end

  def show
    @training = Training.find(params[:id])
    @training_months = Training.real.group_by { |t| t.start_time.beginning_of_month }
  end

  def create_from_exemplary
    from = Training.find(params[:id])
    @training = from.amoeba_dup
    @training.save
    render 'edit'
  end

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(params[:training])
    if @training.save
      redirect_to @training, :notice => "Successfully created training."
    else
      render :action => 'new'
    end
  end

  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])
    if @training.update_attributes(params[:training])
      @training.set_start_time
      redirect_to @training, :notice  => "Successfully updated training."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_url, :notice => "Successfully destroyed training."
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
  def link_to_add_training_segment(name, f, association) 
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', id: "add_training_segment_btn", class: "btn btn-success add_training_segment_btn", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/trainings/_builder_form.html.erb
<%= simple_form_for @training do |f1| %>
  <%= f1.error_notification %>

  <%= f1.input :name %>
  <%= f1.input :city %>
  <%= f1.association :training_types, label: "Wybierz rodzaje szkoleń", as: :check_boxes, :label_method => :label, :value_method => :id %>

  <div id="days" class="clearfix">
    <p>Dni szkoleniowe:</p>
  </div>

  <%= link_to( raw('<i class="icon-plus-sign icon-white"></i> Dodaj dzień'), '#', 
               id: "add_day_btn", class: "btn btn-success add_day_btn", 
               data: {id: "new_id", html: "#{render('day_box')}" } ) %> 

  <ul id="available_segments" class="clearfix connectedSortable">
    <% Segment.all.each do |s| %>
      <%= content_tag(:li, s.name, data: { event_type: s.event_type.id, segment: s.id } ) %>
    <% end -%>
  </ul>

  <%= f1.simple_fields_for :training_segments do |f2| %><% end -%>
  <%= link_to_add_training_segment raw('<i class="icon-plus-sign icon-white"></i> Dodaj segment'), f1, :training_segments %>

  <div class="form-actions">
    <%= f1.button :submit %>
  </div>
<% end %>

    <%# f.input :name %>
    <%# f.input :city %>
    <%# f.input :price_per_person %>
    <%# f.input :start_time %>
    <%# f.input :number_of_days %>
    <%# f.input :number_of_hours %>

    <!-- 
    <ul class="day_box">
      <li class="segment_box">Item 1</li>
      <li class="segment_box">Item 2</li>
      <li class="segment_box">Item 3</li>
      <li class="segment_box">Item 4</li>
      <li class="segment_box">Item 5</li>
    </ul> -->

app/views/trainings/_confirmation_step.html.erb
<div class="form-actions">
  <%= f.button :submit %>
</div>

app/views/trainings/_day_box.html.erb
<ul class="day_box connectedSortable" id="">
  <%= text_field :day_date, Date.new, id: "" %>
  <%= link_to raw('<i class="icon-trash"></i>'), '#', class: "remove_day_btn" %>
</ul>

app/views/trainings/_form.html.erb
<%= simple_form_for @training do |f1| %>
  <%= f1.error_notification %>
  <h3>Dane ogólne</h4>
  <%= f1.input :name, input_html: { class: "input-xxlarge"} %>
  <%= f1.input :city %>
  <%= f1.input :price_per_person %>
  <%= f1.input :introduction %>
  <%= f1.input :description %>

  <h3>Dni szkoleniowe</h4>
  <%= f1.simple_fields_for :training_segments do |f2| %>
    <%= content_tag :strong, f2.object.name %>
    <%= f2.input :number_of_hours %>
    <%= f2.input :start_time, as: :string %> 
    <%= f2.input :scenario %>
  <% end -%>

  <div class="form-actions">
    <%= f1.button :submit %>
  </div>
<% end %>

    <%# f.input :name %>
    <%# f.input :city %>
    <%# f.input :price_per_person %>
    <%# f.input :start_time %>
    <%# f.input :number_of_days %>
    <%# f.input :number_of_hours %>

    <!-- 
    <ul class="day_box">
      <li class="segment_box">Item 1</li>
      <li class="segment_box">Item 2</li>
      <li class="segment_box">Item 3</li>
      <li class="segment_box">Item 4</li>
      <li class="segment_box">Item 5</li>
    </ul> -->

app/views/trainings/_modules_step.html.erb
<%= f.association :segments, as: :check_boxes %>

app/views/trainings/_side_menu.html.erb
<%= content_tag :h4, (link_to "Nasza oferta:", offer_trainings_path) %>
<ul class="well nav nav-list">
  <li class="nav-header">PRINCE 2 FOUNDATION</li>
  <li><a href="/trainings/1">P2F Standard</a></li>
  <li><a href="/trainings/3">P2F Weekend</a></li>
  <li class="nav-header">PRINCE 2 PRACTITIONER</li>
  <li><a href="/trainings/2">P2P Standard</a></li>
  <li><a href="/trainings/4">P2P Weekend</a></li>
  <li class="nav-header">PRINCE 2 COMBO</li>
  <li><a href="/trainings/5">P2F+P2P Combo</a></li>
  <li class="nav-header">ITIL</li>
  <li><a href="/trainings/6">Itil V3</a></li>
</ul>

<% if @training_months %>
  <%= content_tag :h4, (link_to "Harmonogram:", trainings_path) %>
  <ul class="well nav nav-list">
  <% @training_months.each do |month, trainings| %>
    <li class="nav-header"><%= month.strftime("%B %Y") %></li>
    <% trainings.each do |training| %>
      <li><%= link_to (training.start_time.strftime("%d-%m-%Y")+": "+training.name), training_path(training) %></li>
    <% end %>
  <% end %>
  </ul>
<% end -%>

app/views/trainings/_training_segment_fields.html.erb
<%= f.input :segment_id %>
<%= f.input :start_time, as: :string %> 

app/views/trainings/_type_step.html.erb
<%= f.association :training_types, as: :check_boxes %>

app/views/trainings/edit.html.erb
<% title "Edit Training" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @training %> |
  <%= link_to "View All", trainings_path %>
</p>

app/views/trainings/index.html.erb
<% title "Harmonogram" %>

<% content_for :menu do %>

  <%= render 'side_menu' %>

<% end %>

<% content_for :content do %>

  <% @training_months.each do |month, trainings| %>
    <h3><%= month.strftime("%B %Y")%></h3>
    <% trainings.each do |tr| %>
      <%= link_to "zobacz szczegóły", training_path(tr), class: "pull-right" %>
      <%= content_tag :h5, tr.start_time.strftime("%d-%m-%Y") + ": " + tr.name %>
      <%= content_tag :blockquote, raw(tr.introduction) %>
    <% end %>
  <% end %>
<% end -%>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Price Per Person</th>
      <th>Start Time</th>
      <th>Number Of Days</th>
      <th>Number Of Hours</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% for training in @trainings %>
    <tr>
      <td><%= training.name %></td>
      <td><%= training.city %></td>
      <td><%= training.price_per_person %></td>
      <td><%= training.start_time %></td>
      <td><%= training.number_of_days %></td>
      <td><%= training.number_of_hours %></td>
      <td>
      <%= link_to "Show", training, class: 'btn btn-mini btn-success' %>
      <%= link_to "Copy", training, class: 'btn btn-mini btn-info' %>
      <%= link_to "Edit", edit_training_path(training), class: 'btn btn-mini btn-warning' %>
      <%= link_to "Destroy", training, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-mini btn-danger' %>
      <%= link_to "Zapisz się", register_training_orders_path(training), class: 'btn btn-mini btn-success' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<hr>
<p><%= link_to "+ Dodaj Szkolenie", new_training_path, id: "new_training_link" %></p>

app/views/trainings/new.html.erb
<% title "New Training" %>

<%= render 'form' %>

<p><%= link_to "Back to List", trainings_path %></p>

app/views/trainings/offer.html.erb
<% title "Oferta" %>

<% content_for :menu do %>

  <%= render 'side_menu' %>

<% end %>

<% content_for :content do %>
  <%= content_tag :h3, "Zarządzanie Projektami - metodyka PRINCE 2" %>
  <% @trainings.each do |tr| %>
    <% next if tr.id == 6 %>
    <%= link_to "zobacz szczegóły", training_path(tr), class: "pull-right" %>
    <%= content_tag :h5, tr.name %>
    <%= content_tag :blockquote, raw(tr.introduction) %>
  <% end -%>

  <%= content_tag :h3, "Zarządzanie Projektami - narzędzia informatyczne" %>
  <% @trainings.select { |tr| tr.id == 6 }.each do |tr| %>
    <%= link_to "zobacz szczegóły", training_path(tr), class: "pull-right" %>
    <%= content_tag :h5, tr.name %>
    <%= content_tag :blockquote, raw(tr.introduction) %> 
  <% end -%>
<% end %>

app/views/trainings/show.html.erb
<% # encoding: utf-8 %>
<% title "Training" %>

<% content_for :menu do %>

  <%= render 'side_menu' %>

<% end %>

<% content_for :content do %>
  <%= link_to "wróć do oferty", offer_trainings_path %>
  <%= content_tag :h4, "Cena: #{@training.price_per_person} netto", class: "pull-right" %>
  <%= content_tag :h3, @training.name %>
  <%= content_tag :blockquote, raw(@training.introduction) %>

  <ul class="nav nav-tabs">
    <li class="active"><a href="#opis_szkolenia" data-toggle="tab">Opis szkolenia</a></li>
    <li><a href="#harmonogram_szkolenia" data-toggle="tab">Harmonogram szkolenia</a></li>
    <li><a href="#najblisze_terminy" data-toggle="tab">Najbliższe terminy</a></li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Informacje dla klientów <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="#">Informacje organizacyjne</a></li>
        <li><a href="#">Rejestracja - jak zgłosić się na szkolenie</a></li>
        <li><a href="#">Warunki uczestnictwa</a></li>
        <li><a href="#">Płatności</a></li>
        <li><a href="#">Rabaty i promocje</a></li>
        <li class="divider"></li>
        <li><a href="#">Formularz zgłoszeniowy on-line</a></li>
        <li><a href="#">Formularz zgłoszeniowy do pobrania</a></li>
      </ul>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Edytuj", edit_training_path(@training) %></li>
        <li><%= link_to "Kopiuj na nowe", create_from_exemplary_training_path(@training), method: :post %></li>
      </ul>
    </li>
    <%= link_to "Zapisz się", register_training_orders_path(@training), class: 'btn btn-success register_for_training_btn pull-right' %>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="opis_szkolenia"><%= raw @training.description %></div>
    <div class="tab-pane" id="harmonogram_szkolenia"><%= raw @training.schedule %></div>
    <div class="tab-pane" id="najblisze_terminy"><%= raw @training.closest_trainings %></div>
   </div>
  
<% end %>

<!-- <p>
  <%# link_to "Edit", edit_training_path(@training) %> |
  <%# link_to "Destroy", @training, :confirm => 'Are you sure?', :method => :delete %> |
  <%#= link_to "View All", trainings_path %>
</p>
 -->