config/routes.rb
Iqm::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :trainings do
    get 'offer', on: :collection
    post 'create_from_exemplary', on: :member
    resources :orders do
      collection do
        get   'register'
        post  'preview'
        post  'confirm'
      end
    end
  end

  resources :segments

  resources :event_types do
    resources :segments, only: :index
  end

  resources :companies

  resources :clients

  resources :orders

  resources :offers, shallow: true do
    resources :quotes do
      resources :income_variants,:cost_items
    end
  end

  root to: 'offers#index'

end

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= msg %> 
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">IQM</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <%= menu_item("Oferty", offers_path) %>
          <%= menu_item("Szkolenia", offer_trainings_path) %>
          <%= menu_item("Zamówienia", orders_path) %>
          <%= menu_item("Osoby", clients_path) %>
          <%= menu_item("Firmy", companies_path) %>
        </ul>
        <ul class="nav pull-right">
          <li class="dropdown">
            <% menu_label = current_user ? " #{current_user.email}" : " konto użytkownika" %>
            <%= link_to iconize("user",true) + menu_label + raw("<b class=\"caret\"></b>"), '#', class: "dropdown-toggle", data: { toggle: "dropdown"} %>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <% if current_user %>
                <%= content_tag(:li, link_to("Wyloguj się", logout_path)) %>
              <% else %>
                <%= content_tag(:li, link_to("Zaloguj się", login_path)) %>
                <%= content_tag(:li, link_to("Zarejestruj się", signup_path)) %>
              <% end -%>
            </ul>
          </li>
        </ul>
          


        <!--         <form class="navbar-form pull-right">
          <input class="span2" type="text" placeholder="Email">
          <input class="span2" type="password" placeholder="Password">
          <button type="submit" class="btn">Sign in</button>
        </form> -->
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>