config/routes.rb
Iqm::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :trainings do
    get 'offer', on: :collection
    post 'create_from_exemplary', on: :member
    resources :orders do
      collection do
        get   'register'
        post  'preview'
        post  'confirm'
      end
    end
  end

  resources :segments

  resources :event_types do
    resources :segments, only: :index
  end

  resources :companies

  resources :clients

  resources :orders

  resources :offers, shallow: true do
    resources :quotes do
      resources :income_variants,:cost_items
    end
  end

  root to: 'offers#index'

end

app/models/event_type.rb
# == Schema Information
#
# Table name: event_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class EventType < ActiveRecord::Base  
  has_many :quotes
  has_many :trainings, foreign_key: "training_type_id"
  has_many :products, through: :event_type_products
  has_many :event_type_products
  has_many :segments
  has_many :event_type_trainings
  has_many :trainings, through: :event_type_trainings
  attr_accessible :name, :description, :default_price_per_person, :default_number_of_days 
  validates :name, presence: true

  def label
    name + " (#{default_number_of_days})"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    # 3.times { @event.event_participations.build.build_participant }
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to @event, :notice => "Successfully created event."
    else
      render :action => 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event, :notice  => "Successfully updated event."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, :notice => "Successfully destroyed event."
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def link_to_add_participant_row_old(name, f, association) 
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      # new_participant = Participant.new
      # builder.simple_fields_for :participant, new_participant, defaults: { 
      #                                         label: false, 
      #                                         wrapper_html: { class: '' }, 
      #                                         input_html: { class:'' }
      #                                       } do |participant_builder|
        render 'participant_fields', f: builder, i: raw("<i class=\"icon-star new_row_star\"></i>"), aev: f.object.id, new_obj: true
      # end
    end
    link_to(name, '#', class: "btn btn-success add_participant_btn", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def setup_event(event)
    unless event.errors.any?
      2.times { event.event_participations.build.build_participant }
    end
    event
  end

end

app/views/events/_event_participation_fields.html.erb
<%= f.simple_fields_for :participant, defaults: { 
                                              label: false, 
                                              wrapper_html: { class: '' }, 
                                              input_html: { class:'' }
                                            } do |participant_builder| %>
  <%= render 'participant_fields', f: participant_builder, i: index %>
<% end %> 

app/views/events/_form.html.erb
<%= simple_form_for setup_event(@event), html: { class: 'form-inline'} do |f| %>
  <%= f.error_messages %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Event</legend>

    <%= field_with_prepend f, name: :name, wrapper_html_class: "event_field" %>

    <%= field_with_prepend f, name: :event_type_id, prompt: "Type...", wrapper_html_class: "event_field",
                              input_html_class: "input-small", prepend_text: iconize("list"), collection: EventType.all %>

    <%= field_with_prepend f, name: :date, as: :string, wrapper_html_class: "event_field", 
                              input_html_class: "input-small", prepend_text: iconize("calendar") %>
    
    <%= field_with_prepend f, name: :city, prompt: "City...", wrapper_html_class: "event_field",
                              input_html_class: "input-medium", prepend_text: iconize("screenshot"), collection: f.object.cities %>    
    
    <%= field_with_prepend f, name: :price_per_participant, wrapper_html_class: "event_field", input_html_class: 'input-mini',  
                              prepend_text: "$ /#{iconize("user")}", type: "number", step: 50 %>


    <br class="clearfix" style="float:none; clear: both;" />
    <div class="participants_table_wrapper">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th class="">#</th>
            <th class="">Name</th>
            <th class="">email</th>
            <th class=""><i class="icon-trash"></i></th>
          </tr>
        </thead>
        <tbody>
          <% associated_event = f.object.id %>
          <%= f.simple_fields_for :event_participations do |builder| %>
            <%= render 'participant_fields', f: builder, aev: associated_event, new_obj: false %>
          <% end %>
        </tbody>
      </table>         
      <%= link_to_add_participant_row raw('<i class="icon-plus-sign icon-white"></i> Add Participant'), f, :event_participations %>
    </div>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary', id: 'create_or_update_offer_btn' %>
      <%= link_to 'Cancel', offers_path, :class => 'btn' %>
    </div>

  </fieldset>
<% end %>

app/views/events/_participant_fields.html.erb
<% if f.object.new_record? %>
<% @participant=Participant.new if new_obj %>
<% unless !f.object.new_record? && f.object.attributes['participant_id'].nil? %>
  <tr>
    <%= f.simple_fields_for :participant, @participant, defaults: { label: false, wrapper_html: { class: '' }, input_html: { class:'' } } do |pf| %>
      <td class="no"></td>
      <td class="name">
        <%= pf.input :name %>
      </td>
      <td> <%= pf.input :email %> </td>    
      <%= pf.hidden_field(:id) %>
      <%= pf.hidden_field :associated_event_id, value: aev %>
    <% end -%>
    <td class="trashbin"><%= f.hidden_field :_destroy %><%= link_to raw('<i class="icon-trash"></i>'), '#', class: "remove_event_participation_btn" %></td>
    <%= f.hidden_field :id %>
  </tr>
<% end -%>
<% end -%>

app/views/events/edit.html.erb
<% title "Edit Event" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @event %> |
  <%= link_to "View All", events_path %>
</p>

app/views/events/index.html.erb
<% title "Events" %>
<h1>Events</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th># of part.</th>
      <th>Price / part.</th>
      <th>Event type</th>
      <th>City</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>      
       <tr>
        <td><%= event.id %></td>
        <td><%= link_to event.name, event_path(event) %></td>
        <td><%= quotes_number_badge(event.participants.size) %></td>
        <td><%= event.price_per_participant %></td>
        <td><%= event.event_type.try(:name) %></td>
        <td><%= event.city %></td>
        <td>
          <%# link_to 'Show', offer , class: 'btn btn-mini' %>
          <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-mini btn-info' %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to '+ New Event', new_event_path, class: 'btn btn-success', id: 'new_event_btn' %>

app/views/events/new.html.erb
<% title "New Event" %>

<%= render 'form' %>

<p><%= link_to "Back to List", events_path %></p>

app/views/events/show.html.erb
<% title "Event" %>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>
<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>
<p>
  <strong>Price Per Participant:</strong>
  <%= @event.price_per_participant %>
</p>
<p>
  <strong>Event Type:</strong>
  <%= @event.event_type_id %>
</p>
<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <%= link_to "Edit", edit_event_path(@event) %> |
  <%= link_to "Destroy", @event, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", events_path %>
</p>