config/routes.rb
Iqm::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :trainings do
    get 'offer', on: :collection
    post 'create_from_exemplary', on: :member
    resources :orders do
      collection do
        get   'register'
        post  'preview'
        post  'confirm'
      end
    end
  end

  resources :segments

  resources :event_types do
    resources :segments, only: :index
  end

  resources :companies

  resources :clients

  resources :orders

  resources :offers, shallow: true do
    resources :quotes do
      resources :income_variants,:cost_items
    end
  end

  root to: 'offers#index'

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  belongs_to :event_type
  has_many   :training_segments
  has_many   :trainings, through: :training_segments
  attr_accessible :event_type_id, :number_of_hours, :name, :scenario, :default_lineup
  #default_scope include: :event_type, order: 'event_types.id, default_lineup'

  validates :name, presence: true
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_filter :find_event_type, only: :index

  def index
    @segments = @event_type ? @event_type.segments : Segment.all
  end

  def show
    @segment = Segment.find(params[:id])
  end

  def new
    @segment = Segment.new
  end

  def create
    @segment = Segment.new(params[:segment])
    if @segment.save
      redirect_to @segment, :notice => "Successfully created segment."
    else
      render :action => 'new'
    end
  end

  def edit
    @segment = Segment.find(params[:id])
  end

  def update
    @segment = Segment.find(params[:id])
    if @segment.update_attributes(params[:segment])
      redirect_to @segment, :notice  => "Successfully updated segment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @segment = Segment.find(params[:id])
    @segment.destroy
    redirect_to segments_url, :notice => "Successfully destroyed segment."
  end

  protected
  def find_event_type
    if params[:event_type_id]
       @event_type = EventType.find(params[:event_type_id])
    end
  end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= simple_form_for @segment do |f| %>
  <%= f.error_messages %>
  <%= f.input :name %>
  <%= f.input :hours %>
  <%= f.input :scenario %>
  <%= f.association :event_type, label: EventType.model_name.human %>
  <%= f.input :default_lineup %>
  <%= f.submit %>
<% end %>

app/views/segments/edit.html.erb
<% title "Edit Segment" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @segment %> |
  <%= link_to "View All", segments_path %>
</p>

app/views/segments/index.html.erb
<% title "Segments" %>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours</th>
      <th>Scenario</th>
      <th>Event Type</th>
      <th>Kolejność</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% for segment in @segments %>
    <tr>
      <td><%= segment.name %></td>
      <td><%= segment.number_of_hours %></td>
      <td><%= raw segment.scenario %></td>
      <td><%= segment.event_type_id %></td>
      <td><%= segment.default_lineup %></td>
      <td>
      <%= link_to "Show", segment, class: 'btn btn-mini btn-success' %>
      <%= link_to "Edit", edit_segment_path(segment), class: 'btn btn-mini btn-warning' %>
      <%= link_to "Destroy", segment, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-mini btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<p><%= link_to "+ Dodaj Segment", new_segment_path %></p>

app/views/segments/new.html.erb
<% title "New Segment" %>

<%= render 'form' %>

<p><%= link_to "Back to List", segments_path %></p>

app/views/segments/show.html.erb
<% title "Segment" %>

<p>
  <strong>Name:</strong>
  <%= @segment.name %>
</p>
<p>
  <strong>Hours:</strong>
  <%= @segment.hours %>
</p>
<p>
  <strong>Scenario:</strong>
  <%= raw @segment.scenario %>
</p>
<p>
  <strong>Event Type:</strong>
  <%= @segment.event_type.name %>
</p>
<p>
  <strong>Kolejność</strong>
  <%= @segment.default_lineup %>
</p>

<p>
  <%= link_to "Edit", edit_segment_path(@segment) %> |
  <%= link_to "Destroy", @segment, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", segments_path %>
</p>